<a href="https://colab.research.google.com/github/xqyn/BI-BE-CS-183-2023-HW/blob/main/HW1/Problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# This is  used to time the running of the notebook
import time
start_time = time.time()

In [9]:
#import packages
import numpy as np
import pandas as pd

In [75]:
#gene expression matrix
G = np.array([[1,2,3,3],[3,1,9,4],[1,4,3,5]])

In [82]:
G1 = G.copy()
#G1 = pd.DataFrame(G)
G1

array([[1, 2, 3, 3],
       [3, 1, 9, 4],
       [1, 4, 3, 5]])

In [86]:
pd.DataFrame(G)

0  1  2  3
0  1  2  3  3
1  3  1  9  4
2  1  4  3  5

Consider the following gene expression matrix G, containing the expression level of four genes across three cells. The i-th row of G represents the expression level of all genes in the i-th cell, and the j-th column represents the expression level of the j-th gene across all cells.

A Colab notebook has been created to help with computation if needed. Note that when submitting your homework you must submit a link to a copy of this notebook if you use and modify it.


1.  (2 points) Which cell has the highest expression level of gene 2 (index starts from 1)?
2.  (2 points) Which gene is most highly expressed in cell 2?
3.  One of the most fundamental characteristics of a matrix A is its rank, which corresponds
to the maximal number of linearly independent columns/rows of A. A set of vectors
v1, v2, . . . , vn are linearly independent if the equation
a1v1 + a2v2 + · · · + anvn = 0
can only be satisfied by ai = 0 for i = 1, . . . , n.

  i. (2 points) Find the rank of G

  ii. (2 points) What does the rank of G suggest in terms of the relationship in expression
level between the four genes?

In [ ]:
# (2 points) Which cell has the highest expression level of gene 2 (index starts from 1)?

# Cell 3

# (2 points) Which gene is most highly expressed in cell 2?

# Gene 3

# One of the most fundamental characteristics of a matrix A is its rank,
#which corresponds to the maximal number of linearly independent columns/rows of A.
#A set of vectors v1, v2, . . . , vn are linearly independent if the equation
#a1v1 + a2v2 + · · · + anvn = 0
#can only be satisfied by ai = 0 for i = 1, . . . , n.

# i. (2 points) Find the rank of G
# check linear dependent
#col3 = 3x col1
# col4 = col1 + col2
# rank 2


# ii. (2 points) What does the rank of G suggest in terms of the relationship in expression level between the four genes?
# gene 3 expression is relative the gene 1
# gene 4 expression is relative the both gene 1 and gene2

In [19]:
# (d) Suppose you are interested in selecting only highly expressed genes for further analysis.

# i. (2 points) Find a vector v such that the product vTG contains the mean expression level for every gene in G.

# as n = 4 genes -> v^T = [1/4, 1/4, 1/4, 1/4]
n = 3
v = [1/n,1/n,1/n]
v

[0.3333333333333333, 0.3333333333333333, 0.3333333333333333]

In [33]:
# ii. (2 points) Find the mean expression level for each gene in G.
np.transpose(v) @ G

array([1.66666667, 2.33333333, 5.        , 4.        ])

In [ ]:
# iii. (4 points) Find a matrix P, such that GP is a new gene expression matrix that
# contains, for each cell, only the expression level of the two genes with the highest
# mean expression.

In [90]:
P = np.array([[0,0],[0,0],[1,0],[0,1]])
P

array([[0, 0],
       [0, 0],
       [1, 0],
       [0, 1]])

In [91]:
G@P

array([[3, 3],
       [9, 4],
       [3, 5]])

In [93]:
for i in range(G.shape[0]):
  max2, max1 = sorted(G[i])[-2:]
  G1[i][np.where(G1[i] < max2)] = 0
G1

array([[0, 0, 3, 3],
       [0, 0, 9, 4],
       [0, 4, 0, 5]])

In [ ]:
# (e) In many practical applications, we are often interested in finding cells that are “similar”
# to one another in terms of their gene expression profiles, where the gene expression profile
# of a cell corresponds to a row vector of the gene expression matrix. Finding how similar
# two cells are amounts to computing how “close” their corresponding expression vectors
# are under a particular distance function.

# i. (9 points) Consider three valid distance functions between a pair of vectors x and y,
# the L1 distance, L2 distance, and cosine similarity (c),

In [ ]:
# Running time of the notebook
print("{:.2f} minutes".format((time.time()-start_time)/60))

0.00 minutes
